version: '3.8'

services:
  app:
    build: .
    container_name: hire-smart-app
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: npm run start:prod

  db:
    image: postgres:16
    container_name: hiresmart-db
    ports:
      - '5544:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hiresmart-redis
    ports:
      - '6380:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  pgdata:
  redisdata:
